# Site settings
title: Sandown Bay Resource Capital
email: info@sdb-cap.com
description: > # this means to ignore newlines until "baseurl:"
  Sandown Bay Resource Capital is a specialist mining private equity firm. We invest in mining companies globally and work with them to transform and build strong and sustainable businesses.
baseurl: 
url: "http://www.sdb-cap.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: [lib, bin, Gemfile, Gemfile.lock, spec, SpecRunner.html]
sass:
    style: :compressed
gems:
  - jekyll-sitemap
